"""
Constants for raw Redfin column names used in ingestion and transformation.
"""

RAW_HOUSING_REDFIN_CITY = "CITY"
RAW_HOUSING_REDFIN_STATE = "STATE"
RAW_HOUSING_REDFIN_PERIOD_BEGIN = "PERIOD_BEGIN"
RAW_HOUSING_REDFIN_PERIOD_END = "PERIOD_END"
RAW_HOUSING_REDFIN_MEDIAN_SALE_PRICE = "MEDIAN_SALE_PRICE"
RAW_HOUSING_REDFIN_HOMES_SOLD = "HOMES_SOLD"
RAW_HOUSING_REDFIN_INVENTORY = "INVENTORY"
RAW_HOUSING_REDFIN_MEDIAN_DOM = "MEDIAN_DOM"
RAW_HOUSING_REDFIN_PROPERTY_TYPE = "PROPERTY_TYPE"
